# Generated by Django 4.2.23 on 2025-07-31 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('result', models.TextField()),
                ('action_type', models.CharField(choices=[('code_generation', 'Code Generation'), ('debugging', 'Debugging'), ('git_operation', 'Git Operation'), ('analyze_file', 'Analyze File'), ('generate_ideas', 'Generate Ideas'), ('general_ai', 'General AI')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
